version: '3.8'
# services / containers
services:
  # express app
  nest-up-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-up-api
    image: nest-up-api:1.0.0
    restart: always
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      JWT_SECRET: UKHUWAHPROJECTINDONESIA
      # for prisma
      DATABASE_URL: mysql://root:my-secret-pw@localhost:3306/ukhuwah_project
    volumes:
      - nest-up-api-public:/app/public
    networks:
      - app-up-website
    depends_on:
      - mysql_up

  # mysql database
  mysql_up:
    container_name: mysql_up
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ukhuwah_project
    volumes:
      - mysql_up:/var/lib/mysql
    networks:
      - app-up-website

# volumes
volumes:
  nest-up-api-log:
    name: nest-up-api-log
  nest-up-api-uploads:
    name: nest-up-api-uploads
  mysql_uda_portfolio:
    name: mysql_uda_portfolio

# networks
networks:
  app-up-website:
    name: app-up-website
    driver: bridge
